### ISSUE TITLE
WIRE on MRI data

### ISSUE THREAD

**Issue by luisdavid64** [vishwa91/wire#16]
Hi @vishwa91 thank you for the nice repo :) I am trying to fit some MRI data with WIRE. However, I tend to get gradient problems as my loss and PSNR goes to NaN after a couple of epochs using the recommended lr and omega and sigma in the range 10-30. I am  able to fit the data with SIREN. Do you maybe have some pointers to use WIRE for this kind of data?

**Comment by vishwa91** [comment]
@luisdavid64 try using a omega/sigma ratio that is smaller than 2. So if you use sigma value of 10, use omega that is 20, no higher. You can circumvent this problem by setting hidden omega to a smaller value, such as 1.

Hope that helps!

**Comment by luisdavid64** [comment]
Thank you that seems to solve the issue!
