### ISSUE TITLE
Question about the image fitting results of SIREN？ 

### ISSUE THREAD

**Issue by liuzhen0212** [vishwa91/wire#24]
Hello, it appears that the paper and supplementary materials do not specify which image was used in Figure 3. Could you provide clarification on this matter?

**Comment by vishwa91** [comment]
We used the Kodak images from here: https://r0k.us/graphics/kodak/

Hope that helps!

**Comment by liuzhen0212** [comment]
Thanks for you reply！Did you use all 24 images or just a single image? It's a massive amount of work to conduct a grid search for image representation.

**Comment by liuzhen0212** [comment]
Hi, could you please explain why the image fitting performance of SIREN on the Kodak dataset appears to be notably superior to the results presented in the paper?

Wire: 
![image](https://github.com/vishwa91/wire/assets/76141000/d8276e90-e522-447e-bd63-70cae7d27043)

**My results (first_omega=80, hidden_omgea=80, learning rate = 5e-4, hidden layers: 2, hidden features: 256):**
![image](https://github.com/vishwa91/wire/assets/76141000/9ad5afde-5de7-4515-81c6-dc5ecc23ac82)
