### ISSUE TITLE
More data for CT

### ISSUE THREAD

**Issue by Aiolus-X** [vishwa91/wire#25]
Dear author, may I ask how could I get more data for the CT reconstruction task? Thank you very much!

**Comment by vishwa91** [comment]
Greetings. We used dataset from here: https://www.cancerimagingarchive.net/ . Hope that helps!

**Comment by Aiolus-X** [comment]
Thank you for the reply! The dataset is too large, how many CT images should I use for a persuasive experimental result?

**Comment by vishwa91** [comment]
@Aiolus-X that depends on your specific use case. Typically you want to do sufficient number of experiments that variance in estimates is low. This could be anywhere from a few ten to several thousand experiments!

**Comment by Aiolus-X** [comment]
Got it! Thank you!
