### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by harshaUwm163** [vishwa91/wire#3]
Currently, I see that only wire_image_denoise.py is in the repo. When will the rest of the files be available?

**Comment by vishwa91** [comment]
Thank you for your message. We are finalizing the scripts, and will upload the rest of the files within a week!

Regards.

**Comment by David-Morales-Norato** [comment]
> 

I will take advantage of this open issue to ask about the Multi-dimensional case for the WIRE in Section 4.4 of the paper. I just wanted to check in and see if you have any plans to publish this in the near future. I couldn't find it on the "coming soon" list in the readme

**Comment by vishwa91** [comment]
@David-Morales-Norato thank you for the note. I will be uploading a 2D version of WIRE along with the rest of the code within the next week.

**Comment by vishwa91** [comment]
All scripts available now. Also added 2D version of wire in `modules/wire2d.py`.
