### ISSUE TITLE
nan value in the output

### ISSUE THREAD

**Issue by jiayangshi** [vishwa91/wire#5]
Hi, thanks for the great work.

When I tried to use your code, I encountered the problem that the output of wire consists of Nan values. Do you aware of it and how do you deal with it?

I used the one in wire2d, 
```
model = INR(in_features=512, hidden_features=256, hidden_layers=8, out_features=1)
input = torch.randn(1, 256, 256, 512)
output = model(input)
torch.isnan(output)
```

Thank you.

**Comment by vishwa91** [comment]
Thank you for pointing out this bug. In general, for WIRE, `omega/sigma < 1.5`, and for 2D WIRE, `omega/sigma < 2.5`. The current code had a default setting of `omega=40, sigma=10`, which resulted in nans. This is due to the exponential part combined with real parts in the expression. 

I have pushed a new code where the default value is `omega=10, sigma=10` .

**Comment by jiayangshi** [comment]
Hi, thank you very much for the quick response! I tried your suggested solution, but still, nans showed up in your current setting. For example, if you can try
```
torch.manual_seed(12345)
model = INR(in_features=512, hidden_features=256, hidden_layers=8, out_features=1)
input = torch.randn(1, 256, 256, 512)
output = model(input)
isnan = torch.isnan(output)
print(f"{isnan.sum()} nans from totoal {isnan.numel()} elements").
```
The output would be 
```
6000 nans from totoal 65536 elements
```

**Comment by vishwa91** [comment]
Each layer of WIRE is of the form `exp(1j * omega0 * linear(x))*exp(-scale0**2 * linear(x))`. Here, if `linear(x)` were real, the first term has an amplitude bound within 1 (complex exponential). However, in deeper layers, `linear(x)` is complex, and hence the real part of `(1j*omega0*linear(x))` could be positive real, resulting in a large number. This results in `nan` values.

Hope that answers your question!

**Comment by vishwa91** [comment]
Issue addressed with changed values of scale and omega values.

**Comment by jiayangshi** [comment]
Thank you for your explanation!
