### ISSUE TITLE
numbers of hyperparameter

### ISSUE THREAD

**Issue by jypppppp** [vishwa91/wire#9]
Dear author,

Thanks for your interesting work.

I am sort of confused about why the number of neurons in each layer should be divided. I think the numbers of hyperparameters would not be changed using different activation functions.

Best,

Jason

**Comment by vishwa91** [comment]
Thank you for your note, Jason.

As WIRE uses complex numbers for weights, we effectively have a 2X increase in parameters (real and imaginary part). Hence we reduce the total number of hyperparameters to account for this.

Hope that helps!

**Comment by jypppppp** [comment]
I see. Without changing the model setting, do all the models in the code have the same number of parameters?

**Comment by vishwa91** [comment]
Approximately, yes. You can confirm it with `utils.count_parameters(model)`.

**Comment by jypppppp** [comment]
Thanks for your help!
